server:
    port: ${PORT:8082}
spring:
    redis:
        uri: ${REDIS_URL:redis://default:4njL1mNaNe6Gkepf2gl3cLfna2CHGNDf@viaduct.proxy.rlwy.net:40203}
    application:
        name: user-service
    jpa:
        database: postgresql
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
    datasource:
        url: ${DB_HOST:jdbc:postgresql://monorail.proxy.rlwy.net:38429/railway}
        driver-class-name: org.postgresql.Driver
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:f512DA3E43-cGFE3fbbdb2B5-5BdceaE}
    mail:
        host: ${MAIL_HOST:smtp.gmail.com}
        username: ${MAIL_USER:pikapi.anony@gmail.com}
        password: ${MAIL_PASSWORD:sehnwhibxlzjuezp}
        port: ${MAIL_PORT:587}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

jwt:
    secret_key: ${TOKEN_SECRET_KEY:KqLaJQJXIfarUZFJ39BfpcWw9vyx9VMOd5SSLDIsu9ajKavYop96uOez20yCDrucd/s=}
    expired_time: ${TOKEN_EXPIRED_TIME:7200000 } # 2 hours
otp:
    expired_time: ${OTP_EXPIRED_TIME:300000}

management:
    endpoint:
        health:
            show-details: always

#eureka:
#    client:
#        service-url:
#            defaultZone: ${DISCOVERY_URL:https://discovery-aoyd.onrender.com/eureka}
#    instance:
##    prefer-ip-address: true

